sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
- '8'
- '7'
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
jobs:
  include:
    - stage: publish
      install: skip
      script: skip
      deploy:
        provider: npm
        email: "jsachs8@gmail.com"
        api_key:
          secure: l1cNZXdC3ZZkGqXdwFk+pVtjTJL0952p12sUt/Q7rqGo55hX4ThBO5aIOiPjp8Ktel8YtTD71TSSYP7hSqkHAMA4PeDDD8ftvrQhAis9v1SOhQ5dpeXs+GlUby1QcneWxcy4yVSP/kS+34RyCTUMfE9mlMI1zhU1VY2J7ZDJhAU7Sf7uPWf4Z4BQACwx18sN7xqj9eSLmkEGS998a0184vroydPfkRxTyAaKT20RG14Bv57NpEDyNyiRCXz3E1PYMUuvHnxTfC24VmRsTd5Qfyzg6FnOu31vd0C8//N6gncw2Yi6L0ColwLlKGVL8V9wz8lFZDeCS9oHG6ABnS/+a3zkNPk3o7yP4WqLKK5BRPVq9ONfpsNlRQYJDcYWxd3NW8RIp59gE4i4TFNzMQ9ACsrVl7QzbREB3CldO4A+UqNR/9r4dCoBJq3Kcwc2qnZaPEZqkq9S52UdlHbFqqOC2v/sgpBwRu/HvpoZH5/HjcgWPNDJ/++X940Dfr405oYjaWTVyuNFLMn5TK14Fu8Q5EbnRHVAM327RK7f5v+406HgIhEjdQbQgi/9rGFuStZQfV8HdP4KGAjkPHgdo131a9SC832WTPASb09creR9zGlKgnvqGXQwXtxyXbUJZYvAtHy1adgzyz5r/wliZTINDoX0Xy/yK7/V5e/NzwDb7jE=
        on:
          branch: master
